### ISSUE TITLE
How to upgrade to PHPBoost 5.1.2

### ISSUE THREAD

**Issue by AlexL777** [PHPBoost/PHPBoost#132]
Hello Developers,

How can I update to PHPBoost 5.1.2? I have a previous version, so I'll probably just need to upload the new version via FTP. Is that correct?

Thanks in Advance.

**Comment by olivierbailly** [comment]
Hello AlexL,
It depends on your PHPBoost's version.
I recommend that you ask your question on the PHPBoost forum https://www.phpboot.com/
Regards,
Olivier.
