### ISSUE TITLE
Countries should be updated..

### ISSUE THREAD

**Issue by pH-7** [PHPBoost/PHPBoost#139]
Yugoslavia is still listed in the countries list. 
https://github.com/PHPBoost/PHPBoost/blob/9959b65caa4e4462b76fa6d217a28b92d62d56a8/stats/lang/english/common.php#L377
https://github.com/PHPBoost/PHPBoost/blob/9959b65caa4e4462b76fa6d217a28b92d62d56a8/lang/english/countries.php#L258

---
Kosovo, Montenegro and Serbie are missing (well, Serbia and Montenegro are put as one).

**Comment by babsolune** [comment]
Thank you for the feedback
