### ISSUE TITLE
PHPBoost non fonctionnel sous Ubuntu 22.04

### ISSUE THREAD

**Issue by BigTwoProduction** [PHPBoost/PHPBoost#148]
Bonjour,

Suite a une montée de version de l'OS sur mon serveur d'Ubuntu 20.04 LTS vers 22.04 LTS, je suis passé d'un PHPBoost fonctionnel a une brique (sic).

L'erreur est la suivante `Fatal error: Allowed memory size of 3221225472 bytes exhausted (tried to allocate 1290240 bytes) in /var/www/html/kernel/framework/util/Debug.class.php on line 221`

Je sais pertinemment que ce qui a engendré ce souci est l'upgrade.
Mais pour un avoir le cœur net, j'ai pris un cobaye, un Pi4, sur lequel je me suis empressé d'installer une version clean d'Ubuntu server 20.04.5 LTS.

J’installe mariadb-server & mariadb-client ainsi que apache2+phpmyadmin -> Aucun souci a l'installation ni a utilisation en local de PHPBoost.
Je recommence la meme opération avec une version Ubuntu Server 22.04 LTS, et comme attendu, a la racine j'ai "Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 237568 bytes) in /var/www/html/kernel/framework/util/Debug.class.php on line 221" sur le Pi4 (Ubuntu 22.04 LTS). Je vais quand meme procéder a l'installation "manuelle", j'ajoute /install.

Je parviens a la premiere étape de l'installation de PHPBoost, le préambule.
Je navigue sans souci jusqu’à l'étape d’après "Configuration base de données", ici je renseigne les bons champs, puis étape suivante, a ce moment PHPBoost doit initier la création de table dans la base.
Ce qu'il réalise mais partiellement, c'est assez long est j'obtiens au final le meme message " Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 237568 bytes) in /var/www/html/kernel/framework/util/Debug.class.php on line 221"
Voici la liste des tables crées (toujours les memes 3 essais):
![image](https://user-images.githubusercontent.com/19799334/199328543-b880cc08-c571-4b7c-bbbe-1b7480d022fb.png)
 
Normalement il devrait y en avoir 69 (de mémoire).
A partir de ce moment impossible de relancer un essai d'installation, message d'erreur directement.

Pour information mon "memory_limit" sur le serveur (pas le Pi4) est de 3G, le paramétrage de php.ini est le meme avant qu’âpres upgrade.

La différence majeure entre les deux version est PHP 7.4 d'un coté et PHP 8.1 de l'autre.

Je ne sais pas si vous étiez au fait de ce souci, et si vous savez comment corriger ce problème.
Vous trouverez ci-joint le fichier error.log du dossier cache.
Il traduit l'état strict après un essai d'installation.
[error.log](https://github.com/PHPBoost/PHPBoost/files/9913668/error.log)

Je reste disponible pour tout autre test,
Cordialement,
Jordan.

**Comment by babsolune** [comment]
Plop

PHPBoost 5.2, n'est pas optimisé pour PHP 8.1, il faut repasser en PHP 8.0

En pratique, modifier le [premier fichier (5.2)](https://github.com/PHPBoost/PHPBoost/blob/5.2/kernel/framework/io/db/driver/mysql/MySQLSelectQueryResult.class.php) incriminé, en se calquant sur sa version [dev (6.0)](https://github.com/PHPBoost/PHPBoost/blob/master/kernel/framework/io/db/driver/mysql/MySQLSelectQueryResult.class.php) améliorera grandement les choses pour l'installation mais il restera des erreurs (non bloquantes)

La version 6.0 de PHPBoost, optimisée pour PHP 8.1 ne devrait plus trop tarder

**Comment by babsolune** [comment]
Plop

j'ai fait un [commit](https://github.com/PHPBoost/PHPBoost/commit/ec27e03e184bbda3ebadb0c562c60905c35bf00c) sur la branche 5.2 pour la compatibilité php 8.1

à tester pour voir si ça résout le problème ;)

**Comment by BigTwoProduction** [comment]
Plop :)

Alors suite au remplacement du fichier MySQLSelectQueryResult.class.php de la version 5.2 par la version en 6.0 dev. L'installation sur Ubuntu 22.04 LTS avec php 8.1 ne pose plus de souci majeur :+1: 

Et concernant une installation existante migrée d'Ubuntu 20.04 LTS vers Ubuntu 22.04 LTS, donc de PHP 7.4 vers 8.1, cela corrige majoritairement le problème !.

Parfois l'erreur s'affiche encore (1 seul fois en 1 jour) mais ce fix me/nous (tous les utilisateur de PHPBoost) de réaliser la migration lors de la sortie de PHPBoost 6 pour les gens qui auront comme moi migré vers la 22.04 LTS avant la sortie de PHPBoost 6.0 :)

Je vois passer des erreurs de dépréciation mais sans impact sur le fonctionnement, tel que `explode(): Passing null to parameter #2 ($string) of type string is deprecated`

Souhaitez-vous que j'incorpore toutes les modifications que vous avez faite sur la branche 5.2 avec votre dernier commit afin de vous confirmer le bon fonctionnement ?

Quoi qu'il en soit un grand merci :)
Bonne journée,
Jordan.

**Comment by babsolune** [comment]
Plop

> Souhaitez-vous que j'incorpore manuellement...

oui ça serait bien pour voir les erreurs qui resteraient

une version 5.2.13 sera mise à disposition issue des nouveaux commits avant la release de la 6.0

**Comment by BigTwoProduction** [comment]
Plop,

Premier retour sur une installation fraîche de PHPBosst sur la branche 5.2 depuis github a ce commit https://github.com/PHPBoost/PHPBoost/commit/fb5eaa4a4a222a909b75ca0ce193c5cb65707317

L’installation ce passe bien mais a l'utilisation quelques erreurs composé de majoritairement 
`Implicit conversion from float xxx.xx to int loses precision` (a mon avis problème de champ dans la base) ainsi qu'une unique erreur apparu devant moi une unique fois `Duplicate entry '4-11-2022' for key 'stats_day'`

Je vous joint le fichier d'erreur [error.log](https://github.com/PHPBoost/PHPBoost/files/9945536/error.log).

Pour une install existante, lorsque j'ai mis tout les fichiers modifiés par les deux dernier commits cela ne fonctionnait pas, la navigateur me retournait "problème d'encodage" sans aucune erreur autres (ni apache, ni PHPBoost).
Je continue mon investigation pour essayer d'apporter de l'eau au moulin :)

Bonne journée (pluvieuse)
Jordan

**Comment by babsolune** [comment]
Merci pour ce retour

**Comment by babsolune** [comment]
La nouvelle version 6.0 est compatible PHP 8.1 mysql 8
