### ISSUE TITLE
Mise a jour PhpBoost depuis le CMS - Une erreur s'est produite lors de l'opération

### ISSUE THREAD

**Issue by BigTwoProduction** [PHPBoost/PHPBoost#157]
Bonjour,

J'avais remonté ce souci en octobre 2023, depuis pas de nouvelles. Je suis toujours en version Phpboost 6.0.0.
Lorsque l'on clique sur "Installer" pour par exemple "Noyau - 6.0.1" il en résulte l'erreur suivante 
_"Une erreur s'est produite lors de l'opération"_

De même pour les mises a jour "Noyau 6.0.2" et "Noyau 6.0.3".
Voici l'erreur remontée dans _"erreurs archivées"_
![image](https://github.com/PHPBoost/PHPBoost/assets/19799334/38a48c01-be67-43ed-8f56-7b9c952a84f3)

**_Analyse pour la MAJ du 6.0.0 vers 6.0.1:_**
Cette erreur me surprend car en prenant le lien du fichier diff-phpboost-6.0.0-to-phpboost-6.0.1.zip, il m'est possible depuis la même IP que mon serveur de télécharger le fichier (md5: d509db6e5460f5a048ff99fb2cc110bc | taille 194237).

Néanmoins je constate que le fichier téléchargé dans /var/www/html/cache n'a pas la bonne taille lorsque je procède a la mise a jour par le menu d'administration (taille 6057). Ce qui provoque l'erreur suivante.

` 
Fatale : Invalid or uninitialized Zip object
 
[0] /kernel/framework/helper/FileSystemHelper.class.php:139 - ZipArchive->extractTo()
[1] /admin/updates/detail.php:80 - FileSystemHelper::download_remote_file()
[URL] /admin/updates/detail.php?identifier=d05a307f91bdcf3381947ee65e0173cc
 `
![image](https://github.com/PHPBoost/PHPBoost/assets/19799334/acfb648d-c0c9-414a-be89-5abf71eeb09e)

Le fichier zip de la maj différentielle est bien crée mais ne contient rien si ce n'est le message d'erreur de l'hébergeur en HTTP 429.

_Cette requête a été bloquée par une sécurité activée sur l'hébergement, suite à de trop nombreuses
              tentatives d'accès détecté (Rate-limit).
              Si vous êtes le webmaster de ce site, vous pouvez désactiver cette sécurité depuis votre compte cPanel._

Ci-joint le fichier .zip issu du téléchargement de la maj 
[diff-phpboost-6.0.0-to-phpboost-6.0.1.zip](https://github.com/PHPBoost/PHPBoost/files/15059411/diff-phpboost-6.0.0-to-phpboost-6.0.1.zip)

J'avais déjà rencontré le souci avec la maj précédente. J'avais a l'époque téléchargé a la main le fichier déposé et décompressé le dossier de la maj dans le dossier suivant /var/www/html/cache/phpboost-diff
Si pour le moment il faut procéder de la sort, dites le moi :)

Bonne journée
Restant disponible,
Jordan.

**Comment by babsolune** [comment]
Désolé du délai
il nous faudrait les logs apaches à la prochaine maj pour pouvoir étudier le problème plus en profondeur

**Comment by BigTwoProduction** [comment]
Plop,

Pas de souci !
A priori @MaxenceCauderlier a soumis un commit qui a été merge.
Merci :)

Dois-je passer le maj depuis la 6.0.1 vers 6.0.3 en "manuel" ou souhaitez vous que je test ce fix en modifiant les deux fichiers concerné puis en effectuant les maj par le panel d’administration ?

Bonne journée,
Jordan.

**Comment by BigTwoProduction** [comment]
Bonjour @MaxenceCauderlier,

Je vous confirme qu'a la suite du changement de ces deux fichiers, j'ai pu mettre a jour de la version 6.0.0 vers la 6.0.3 au travers du panel d'administration sans erreur !
![image](https://github.com/PHPBoost/PHPBoost/assets/19799334/38c31bfe-2c8d-4f85-9894-49bb610da2c7)

j'aurais pu faire les maj bien avant mais je savais qu'une âme charitable allait soumettre un fix a tester, c'est chose faite. 
Merci :)

**Comment by MaxenceCauderlier** [comment]
Merci pour tes retours, nickel !
